### ISSUE TITLE
freemarker 2.3.23 support?

### ISSUE THREAD

**Issue by puntogil** [coconut2015/cookcc#31]
hi
try to build with freemarker 2.3.23, but build fails
any plan to upgrade freemarker?
thanks in advance
regards
```
Buildfile: /builddir/build/BUILD/cookcc-d4354efd653a5bdd82550be35b9a6ea2d50da84a/build.xml
init:
    [mkdir] Created dir: /builddir/build/BUILD/cookcc-d4354efd653a5bdd82550be35b9a6ea2d50da84a/dist
compile:
    [mkdir] Created dir: /builddir/build/BUILD/cookcc-d4354efd653a5bdd82550be35b9a6ea2d50da84a/cookcc_classes
    [mkdir] Created dir: /builddir/build/BUILD/cookcc-d4354efd653a5bdd82550be35b9a6ea2d50da84a/cookcc_classes
    [javac] Compiling 130 source files to /builddir/build/BUILD/cookcc-d4354efd653a5bdd82550be35b9a6ea2d50da84a/cookcc_classes
    [javac] warning: [options] bootstrap class path not set in conjunction with -source 1.7
    [javac] /builddir/build/BUILD/cookcc-d4354efd653a5bdd82550be35b9a6ea2d50da84a/src/freemarker/core/ActionCodeBI.java:44: error: ActionCodeBI is not abstract and does not override abstract method _eval(Environment) in Expression
    [javac] public class ActionCodeBI extends BuiltIn
    [javac]        ^
    [javac] /builddir/build/BUILD/cookcc-d4354efd653a5bdd82550be35b9a6ea2d50da84a/src/freemarker/core/ActionCodeBI.java:52: error: method does not override or implement a method from a supertype
    [javac] 	@Override
    [javac] 	^
    [javac] /builddir/build/BUILD/cookcc-d4354efd653a5bdd82550be35b9a6ea2d50da84a/src/freemarker/core/ActionCodeBI.java:55: warning: [deprecation] getAsTemplateModel(Environment) in Expression has been deprecated
    [javac] 		TemplateModel model = target.getAsTemplateModel (env);
    [javac] 		                            ^
    [javac] /builddir/build/BUILD/cookcc-d4354efd653a5bdd82550be35b9a6ea2d50da84a/src/freemarker/core/ActionCodeBI.java:57: error: cannot find symbol
    [javac] 			throw invalidTypeException (model, target, env, "string");
    [javac] 			      ^
    [javac]   symbol:   method invalidTypeException(TemplateModel,Expression,Environment,String)
    [javac]   location: class ActionCodeBI
    [javac] /builddir/build/BUILD/cookcc-d4354efd653a5bdd82550be35b9a6ea2d50da84a/src/freemarker/core/HexBI.java:40: error: HexBI is not abstract and does not override abstract method _eval(Environment) in Expression
    [javac] public class HexBI extends BuiltIn
    [javac]        ^
    [javac] /builddir/build/BUILD/cookcc-d4354efd653a5bdd82550be35b9a6ea2d50da84a/src/freemarker/core/HexBI.java:48: error: method does not override or implement a method from a supertype
    [javac] 	@Override
    [javac] 	^
    [javac] /builddir/build/BUILD/cookcc-d4354efd653a5bdd82550be35b9a6ea2d50da84a/src/freemarker/core/HexBI.java:51: warning: [deprecation] getAsTemplateModel(Environment) in Expression has been deprecated
    [javac] 		TemplateModel model = target.getAsTemplateModel (env);
    [javac] 		                            ^
    [javac] /builddir/build/BUILD/cookcc-d4354efd653a5bdd82550be35b9a6ea2d50da84a/src/freemarker/core/HexBI.java:53: error: cannot find symbol
    [javac] 			throw invalidTypeException (model, target, env, "number");
    [javac] 			      ^
    [javac]   symbol:   method invalidTypeException(TemplateModel,Expression,Environment,String)
    [javac]   location: class HexBI
    [javac] /builddir/build/BUILD/cookcc-d4354efd653a5bdd82550be35b9a6ea2d50da84a/src/freemarker/core/JavaStringBI.java:44: error: JavaStringBI is not abstract and does not override abstract method _eval(Environment) in Expression
    [javac] public class JavaStringBI extends BuiltIn
    [javac]        ^
    [javac] /builddir/build/BUILD/cookcc-d4354efd653a5bdd82550be35b9a6ea2d50da84a/src/freemarker/core/JavaStringBI.java:63: error: method does not override or implement a method from a supertype
    [javac] 	@Override
    [javac] 	^
    [javac] /builddir/build/BUILD/cookcc-d4354efd653a5bdd82550be35b9a6ea2d50da84a/src/freemarker/core/JavaStringBI.java:66: warning: [deprecation] getAsTemplateModel(Environment) in Expression has been deprecated
    [javac] 		TemplateModel model = target.getAsTemplateModel (env);
    [javac] 		                            ^
    [javac] /builddir/build/BUILD/cookcc-d4354efd653a5bdd82550be35b9a6ea2d50da84a/src/freemarker/core/JavaStringBI.java:68: error: cannot find symbol
    [javac] 			throw invalidTypeException (model, target, env, "array");
    [javac] 			      ^
    [javac]   symbol:   method invalidTypeException(TemplateModel,Expression,Environment,String)
    [javac]   location: class JavaStringBI
    [javac] /builddir/build/BUILD/cookcc-d4354efd653a5bdd82550be35b9a6ea2d50da84a/src/freemarker/core/JavaStringResourceBI.java:45: error: JavaStringResourceBI is not abstract and does not override abstract method _eval(Environment) in Expression
    [javac] public class JavaStringResourceBI extends BuiltIn
    [javac]        ^
    [javac] /builddir/build/BUILD/cookcc-d4354efd653a5bdd82550be35b9a6ea2d50da84a/src/freemarker/core/JavaStringResourceBI.java:68: error: method does not override or implement a method from a supertype
    [javac] 	@Override
    [javac] 	^
    [javac] /builddir/build/BUILD/cookcc-d4354efd653a5bdd82550be35b9a6ea2d50da84a/src/freemarker/core/JavaStringResourceBI.java:71: warning: [deprecation] getAsTemplateModel(Environment) in Expression has been deprecated
    [javac] 		TemplateModel model = target.getAsTemplateModel (env);
    [javac] 		                            ^
    [javac] /builddir/build/BUILD/cookcc-d4354efd653a5bdd82550be35b9a6ea2d50da84a/src/freemarker/core/JavaStringResourceBI.java:73: error: cannot find symbol
    [javac] 			throw invalidTypeException (model, target, env, "array");
    [javac] 			      ^
    [javac]   symbol:   method invalidTypeException(TemplateModel,Expression,Environment,String)
    [javac]   location: class JavaStringResourceBI
    [javac] /builddir/build/BUILD/cookcc-d4354efd653a5bdd82550be35b9a6ea2d50da84a/src/freemarker/core/TypeBI.java:47: error: TypeBI is not abstract and does not override abstract method _eval(Environment) in Expression
    [javac] public class TypeBI extends BuiltIn
    [javac]        ^
    [javac] /builddir/build/BUILD/cookcc-d4354efd653a5bdd82550be35b9a6ea2d50da84a/src/freemarker/core/TypeBI.java:55: error: method does not override or implement a method from a supertype
    [javac] 	@Override
    [javac] 	^
    [javac] /builddir/build/BUILD/cookcc-d4354efd653a5bdd82550be35b9a6ea2d50da84a/src/freemarker/core/TypeBI.java:58: warning: [deprecation] getAsTemplateModel(Environment) in Expression has been deprecated
    [javac] 		TemplateModel model = target.getAsTemplateModel (env);
    [javac] 		                            ^
    [javac] /builddir/build/BUILD/cookcc-d4354efd653a5bdd82550be35b9a6ea2d50da84a/src/freemarker/core/TypeBI.java:60: error: cannot find symbol
    [javac] 			throw invalidTypeException (model, target, env, "bean");
    [javac] 			      ^
    [javac]   symbol:   method invalidTypeException(TemplateModel,Expression,Environment,String)
    [javac]   location: class TypeBI
    [javac] /builddir/build/BUILD/cookcc-d4354efd653a5bdd82550be35b9a6ea2d50da84a/src/org/yuanheng/cookcc/codegen/TemplatedCodeGen.java:68: warning: [deprecation] Configuration() in Configuration has been deprecated
    [javac] 		Configuration cfg = new Configuration ();
    [javac] 		                    ^
    [javac] /builddir/build/BUILD/cookcc-d4354efd653a5bdd82550be35b9a6ea2d50da84a/src/org/yuanheng/cookcc/codegen/TemplatedCodeGen.java:90: warning: [deprecation] BEANS_WRAPPER in ObjectWrapper has been deprecated
    [javac] 		cfg.setObjectWrapper (ObjectWrapper.BEANS_WRAPPER);
    [javac] 		                                   ^
    [javac] 15 errors
    [javac] 8 warnings
BUILD FAILED
```

**Comment by coconut2015** [comment]
I am still using 2.3.15.  I have no plan to upgrade it since that version is good enough.
